CREATE TABLE IF NOT EXISTS users (
  id            INT GENERATED BY DEFAULT AS IDENTITY,
  username      TEXT UNIQUE NOT NULL,
  password      TEXT NOT NULL,
  current_score INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sessions (
  id          TEXT PRIMARY KEY,
  user_id     INT REFERENCES users(id) ON DELETE CASCADE,
  expires_at  TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS scores (
  id          INT GENERATED BY DEFAULT AS IDENTITY,
  user_id     INT REFERENCES users(id) ON DELETE CASCADE,
  score_value INT NOT NULL,
  timestamp   TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS game_state (
  id            INT GENERATED BY DEFAULT AS IDENTITY,
  user_id       INT REFERENCES users(id) ON DELETE CASCADE,
  player_hp     INT NOT NULL,
  current_score INT DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS battle_state (
  game_state_id INT REFERENCES game_state(id) ON DELETE CASCADE,
  user_id       INT REFERENCES users(id) ON DELETE CASCADE,
  turn_owner    VARCHAR(10) DEFAULT 'player',
  current_state VARCHAR(20) DEFAULT 'active',
  enemy_hp      INT NOT NULL,
  PRIMARY KEY (game_state_id)
);


CREATE TABLE IF NOT EXISTS deck (
  battle_state_id INT REFERENCES battle_state(game_state_id) ON DELETE CASCADE,
  current_hand    TEXT[] DEFAULT '{}',
  draw_pile       TEXT[] DEFAULT '{}',
  discard_pile    TEXT[] DEFAULT '{}',
  PRIMARY KEY (battle_state_id)
);

CREATE TABLE IF NOT EXISTS used_words (
  id        INT GENERATED BY DEFAULT AS IDENTITY,
  state_id  INT REFERENCES battle_state(game_state_id) ON DELETE CASCADE,
  word_text VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS forum_posts (
  id          INT GENERATED BY DEFAULT AS IDENTITY,
  user_id     INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content     VARCHAR(300) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);